// <auto-generated />
using System;
using Data.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Data.Migrations
{
    [DbContext(typeof(ConstantTrialPlotsContext))]
    [Migration("20200419182719_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Data.Models.Breed", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Cipher")
                        .HasColumnName("cipher")
                        .HasColumnType("character varying(255)")
                        .HasMaxLength(255);

                    b.Property<string>("Name")
                        .HasColumnName("name")
                        .HasColumnType("character varying(255)")
                        .HasMaxLength(255);

                    b.HasKey("Id");

                    b.ToTable("Breed");
                });

            modelBuilder.Entity("Data.Models.ForestType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Cipher")
                        .HasColumnName("cipher")
                        .HasColumnType("character varying(255)")
                        .HasMaxLength(255);

                    b.Property<string>("Name")
                        .HasColumnName("name")
                        .HasColumnType("character varying(255)")
                        .HasMaxLength(255);

                    b.HasKey("Id");

                    b.ToTable("ForestType");
                });

            modelBuilder.Entity("Data.Models.TechnicalSuitability", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Chipher")
                        .HasColumnName("chipher")
                        .HasColumnType("character varying(255)")
                        .HasMaxLength(255);

                    b.Property<string>("Name")
                        .HasColumnName("name")
                        .HasColumnType("character varying(255)")
                        .HasMaxLength(255);

                    b.HasKey("Id");

                    b.ToTable("TechnicalSuitability");
                });

            modelBuilder.Entity("Data.Models.Tree", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("IdBreed")
                        .HasColumnName("id_breed")
                        .HasColumnType("integer");

                    b.Property<int>("IdPlot")
                        .HasColumnName("id_plot")
                        .HasColumnType("integer");

                    b.Property<int>("IdProperty")
                        .HasColumnName("id_property")
                        .HasColumnType("integer");

                    b.Property<int>("Number")
                        .HasColumnName("number")
                        .HasColumnType("integer");

                    b.Property<double>("X")
                        .HasColumnName("x")
                        .HasColumnType("double precision");

                    b.Property<double>("Y")
                        .HasColumnName("y")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("IdBreed");

                    b.HasIndex("IdPlot");

                    b.HasIndex("IdProperty");

                    b.ToTable("Tree");
                });

            modelBuilder.Entity("Data.Models.TreeProperty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("Age")
                        .HasColumnName("age")
                        .HasColumnType("integer");

                    b.Property<double?>("CrownDiametrNs")
                        .HasColumnName("crown_diametrNS")
                        .HasColumnType("double precision");

                    b.Property<double?>("CrownDiametrWe")
                        .HasColumnName("crown_diametrWE")
                        .HasColumnType("double precision");

                    b.Property<double?>("CrownLength")
                        .HasColumnName("crownLength")
                        .HasColumnType("double precision");

                    b.Property<double>("DiametrNs")
                        .HasColumnName("diametrNS")
                        .HasColumnType("double precision");

                    b.Property<double>("DiametrWe")
                        .HasColumnName("diametrWE")
                        .HasColumnType("double precision");

                    b.Property<double>("Height")
                        .HasColumnName("height")
                        .HasColumnType("double precision");

                    b.Property<int>("IdCraft")
                        .HasColumnName("id_craft")
                        .HasColumnType("integer");

                    b.Property<int>("IdSuitability")
                        .HasColumnName("id_suitability")
                        .HasColumnType("integer");

                    b.Property<int>("TaxationYear")
                        .HasColumnName("taxationYear")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("IdCraft");

                    b.HasIndex("IdSuitability");

                    b.ToTable("TreeProperty");
                });

            modelBuilder.Entity("Data.Models.TrialPlot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<double>("Az")
                        .HasColumnType("double precision");

                    b.Property<double>("Length")
                        .HasColumnName("length")
                        .HasColumnType("double precision");

                    b.Property<int>("Number")
                        .HasColumnName("number")
                        .HasColumnType("integer");

                    b.Property<double>("Square")
                        .HasColumnName("square")
                        .HasColumnType("double precision");

                    b.Property<int>("Weight")
                        .HasColumnName("weight")
                        .HasColumnType("integer");

                    b.Property<double>("X")
                        .HasColumnName("x")
                        .HasColumnType("double precision");

                    b.Property<double>("Y")
                        .HasColumnName("y")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("TrialPlot");
                });

            modelBuilder.Entity("Data.Models.Years", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("IdForestType")
                        .HasColumnName("id_forestType")
                        .HasColumnType("integer");

                    b.Property<int>("IdPlot")
                        .HasColumnName("id_plot")
                        .HasColumnType("integer");

                    b.Property<int>("Kvartal")
                        .HasColumnName("kvartal")
                        .HasColumnType("integer");

                    b.Property<string>("Leshoz")
                        .IsRequired()
                        .HasColumnName("leshoz")
                        .HasColumnType("character varying(255)")
                        .HasMaxLength(255);

                    b.Property<string>("Lesnichestvo")
                        .IsRequired()
                        .HasColumnName("lesnichestvo")
                        .HasColumnType("character varying(255)")
                        .HasMaxLength(255);

                    b.Property<int>("Vydel")
                        .HasColumnName("vydel")
                        .HasColumnType("integer");

                    b.Property<int>("Year")
                        .HasColumnName("year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("IdForestType");

                    b.HasIndex("IdPlot");

                    b.ToTable("Years");
                });

            modelBuilder.Entity("Data.Models.СraftСategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Chipher")
                        .HasColumnName("chipher")
                        .HasColumnType("character varying(255)")
                        .HasMaxLength(255);

                    b.Property<string>("Name")
                        .HasColumnName("name")
                        .HasColumnType("character varying(255)")
                        .HasMaxLength(255);

                    b.HasKey("Id");

                    b.ToTable("СraftСategory");
                });

            modelBuilder.Entity("Data.Models.Tree", b =>
                {
                    b.HasOne("Data.Models.Breed", "IdBreedNavigation")
                        .WithMany("Tree")
                        .HasForeignKey("IdBreed")
                        .HasConstraintName("Tree_fk1")
                        .IsRequired();

                    b.HasOne("Data.Models.TrialPlot", "IdPlotNavigation")
                        .WithMany("Tree")
                        .HasForeignKey("IdPlot")
                        .HasConstraintName("Tree_fk0")
                        .IsRequired();

                    b.HasOne("Data.Models.TreeProperty", "IdPropertyNavigation")
                        .WithMany("Tree")
                        .HasForeignKey("IdProperty")
                        .HasConstraintName("Tree_fk2")
                        .IsRequired();
                });

            modelBuilder.Entity("Data.Models.TreeProperty", b =>
                {
                    b.HasOne("Data.Models.СraftСategory", "IdCraftNavigation")
                        .WithMany("TreeProperty")
                        .HasForeignKey("IdCraft")
                        .HasConstraintName("TreeProperty_fk1")
                        .IsRequired();

                    b.HasOne("Data.Models.TechnicalSuitability", "IdSuitabilityNavigation")
                        .WithMany("TreeProperty")
                        .HasForeignKey("IdSuitability")
                        .HasConstraintName("TreeProperty_fk0")
                        .IsRequired();
                });

            modelBuilder.Entity("Data.Models.Years", b =>
                {
                    b.HasOne("Data.Models.ForestType", "IdForestTypeNavigation")
                        .WithMany("Years")
                        .HasForeignKey("IdForestType")
                        .HasConstraintName("Years_fk0")
                        .IsRequired();

                    b.HasOne("Data.Models.TrialPlot", "IdPlotNavigation")
                        .WithMany("Years")
                        .HasForeignKey("IdPlot")
                        .HasConstraintName("Years_fk1")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
